import { validateModel } from './lib.js';

const escape = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
export function documentHtml(input) {
  const model = validateModel(input);
  const sections = model.tables.map(table => {
    const columns = (table.columns || []).map(column => `<tr><td>${escape(column.name)}</td><td><code>${escape(column.dataType || 'Unspecified')}</code></td><td>${escape(column.description)}</td></tr>`).join('');
    const measures = (table.measures || []).map(measure => `<article><h3>${escape(measure.name)}</h3><p>${escape(measure.description)}</p><pre>${escape(measure.expression || 'Expression not supplied')}</pre></article>`).join('');
    const inferred = table.dataTypeInferred && Number.isSafeInteger(table.sampledRowCount) && Number.isSafeInteger(table.rowCount) ? `<p class="note">Types inferred from ${table.sampledRowCount.toLocaleString('en-US')} of ${table.rowCount.toLocaleString('en-US')} data rows. Review inferred types before use.</p>` : '';
    return `<section><h2>${escape(table.name)}</h2><p>${escape(table.description)}</p>${inferred}<table><thead><tr><th>Column</th><th>Type</th><th>Description</th></tr></thead><tbody>${columns}</tbody></table>${measures}</section>`;
  }).join('');
  const relationships = (model.relationships || []).map(relation => `<tr><td>${escape(relation.fromTable)}.${escape(relation.fromColumn)}</td><td>${escape(relation.toTable)}.${escape(relation.toColumn)}</td><td>${escape(relation.cardinality || 'Unspecified')}</td><td>${escape(relation.crossFilteringBehavior || 'Unspecified')}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(model.name || 'Power BI model')} — Documentation</title><style>body{font:15px/1.7 system-ui,sans-serif;margin:0;color:#182334;background:#f5f7fa}main{max-width:1060px;margin:auto;padding:48px 24px}header{border-bottom:3px solid #5b54d6;padding-bottom:24px}h1{font-size:34px;line-height:1.2}h2{margin:38px 0 12px;color:#3730a3}h3{margin-top:24px}section,article{break-inside:avoid}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:10px 12px;border:1px solid #d9e0e9;text-align:left;overflow-wrap:anywhere}th{background:#e8edf6}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:18px;background:#111827;color:#d9e8ff;border-radius:8px}code{font-size:12px}.note{background:#ecebff;padding:12px;border-left:3px solid #7062d8}.muted{color:#62728a}@media print{body{background:white}main{padding:0}pre{background:#f0f2f6;color:#182334}}</style></head><body><main><header><p class="muted">POWERBI DOCTOR / MODEL REFERENCE</p><h1>${escape(model.name || 'Power BI model')}</h1><p>${escape(model.description)}</p><p>${model.tables.length} tables · ${model.tables.reduce((count,table)=>count+(table.columns || []).length,0)} columns · ${model.tables.reduce((count,table)=>count+(table.measures || []).length,0)} measures</p></header>${sections}<section><h2>Relationships</h2><table><thead><tr><th>From</th><th>To</th><th>Cardinality</th><th>Filter direction</th></tr></thead><tbody>${relationships}</tbody></table></section><p class="muted">Generated from supplied metadata. Formulas were not executed. PowerBI Doctor.</p></main></body></html>`;
}
